export const boardData = [
    {
      id: "task1",
      title: "Mobile App",
      toDos: [
        {
          id: "1",
          title: "Brainstorming",
          image: [],
          description:
            "Brainstorming brings team members' diverse experience into play. ",
          priority: "low",
          comments: 12,
          files: 0,
          users: ["person1", "person3", "person2"],
          status: "not started",
        },
        {
          id: "2",
          title: "Research",
          image: [],
          description:
            "User research helps you to create an optimal product for users.",
          priority: "high",
          comments: 10,
          files: 3,
          users: ["person4", "person3"],
          status: "not started",
        },
        {
          id: "3",
          title: "Wireframes",
          image: [],
          description:
            "Low fidelity wireframes include the most basic content and visuals.",
          priority: "high",
          comments: 11,
          files: 1,
          users: ["person1", "person3", "person2"],
          status: "not started",
        },
        {
          id: "4",
          title: "Onboarding Illustrations",
          image: ["Onboarding"],
          description: "",
          priority: "low",
          comments: 14,
          files: 15,
          users: ["person3", "person2", "person1"],
          status: "started",
        },
        {
          id: "5",
          title: "Moodboard",
          image: ["Moodboard1", "Moodboard2"],
          description: "",
          priority: "low",
          comments: 9,
          files: 10,
          users: ["person3"],
          status: "started",
        },
        {
          id: "6",
          title: "Mobile App Design",
          image: ["MobileAppDesign"],
          description: "",
          priority: "low",
          comments: 12,
          files: 15,
          users: ["person3", "person2"],
          status: "completed",
        },
        {
          id: "7",
          title: "Design System",
          image: [],
          description: "It just needs to adapt the UI from what you did before ",
          priority: "high",
          comments: 12,
          files: 15,
          users: ["person1", "person3", "person2"],
          status: "completed",
        },
      ],
      favColor: "#7AC555",
    },
    {
      id: "task2",
      title: "Website Redesign",
      toDos: [
        {
          id: "1",
          title: "Brainstorming",
          image: [],
          description:
            "Brainstorming brings team members' diverse experience into play. ",
          priority: "low",
          comments: 12,
          files: 0,
          users: ["person1", "person3", "person2"],
          status: "not started",
        },
        {
          id: 2,
          title: "Research",
          image: [],
          description:
            "User research helps you to create an optimal product for users.",
          priority: "high",
          comments: 10,
          files: 3,
          users: ["person4", "person3"],
          status: "not started",
        },
        {
          id: 3,
          title: "Wireframes",
          image: [],
          description:
            "Low fidelity wireframes include the most basic content and visuals.",
          priority: "high",
          comments: 11,
          files: 1,
          users: ["person1", "person3", "person2"],
          status: "not started",
        },
        {
          id: 4,
          title: "Onboarding Illustrations",
          image: ["Onboarding"],
          description: "",
          priority: "low",
          comments: 14,
          files: 15,
          users: ["person3", "person2", "person1"],
          status: "started",
        },
        {
          id: 5,
          title: "Moodboard",
          image: ["Moodboard1", "Moodboard2"],
          description: "",
          priority: "low",
          comments: 9,
          files: 10,
          users: ["person3"],
          status: "started",
        },
        {
          id: 6,
          title: "Mobile App Design",
          image: ["MobileAppDesign"],
          description: "",
          priority: "completed",
          comments: 12,
          files: 15,
          users: ["person3", "person2"],
          status: "completed",
        },
        {
          id: 7,
          title: "Design System",
          image: [],
          description: "It just needs to adapt the UI from what you did before ",
          priority: "completed",
          comments: 12,
          files: 15,
          users: ["person1", "person3", "person2"],
          status: "completed",
        },
      ],
      favColor: "#FFA500",
    },
    {
      id: "task3",
      title: "Design System",
      toDos: [
        {
          id: "1",
          title: "Brainstorming",
          image: [],
          description:
            "Brainstorming brings team members' diverse experience into play. ",
          priority: "low",
          comments: 12,
          files: 0,
          users: ["person1", "person3", "person2"],
          status: "not started",
        },
        {
          id: 2,
          title: "Research",
          image: [],
          description:
            "User research helps you to create an optimal product for users.",
          priority: "high",
          comments: 10,
          files: 3,
          users: ["person4", "person3"],
          status: "not started",
        },
        {
          id: 3,
          title: "Wireframes",
          image: [],
          description:
            "Low fidelity wireframes include the most basic content and visuals.",
          priority: "high",
          comments: 11,
          files: 1,
          users: ["person1", "person3", "person2"],
          status: "not started",
        },
        {
          id: 4,
          title: "Onboarding Illustrations",
          image: ["Onboarding"],
          description: "",
          priority: "low",
          comments: 14,
          files: 15,
          users: ["person3", "person2", "person1"],
          status: "started",
        },
        {
          id: 5,
          title: "Moodboard",
          image: ["Moodboard1", "Moodboard2"],
          description: "",
          priority: "low",
          comments: 9,
          files: 10,
          users: ["person3"],
          status: "started",
        },
        {
          id: 6,
          title: "Mobile App Design",
          image: ["MobileAppDesign"],
          description: "",
          priority: "completed",
          comments: 12,
          files: 15,
          users: ["person3", "person2"],
          status: "completed",
        },
        {
          id: 7,
          title: "Design System",
          image: [],
          description: "It just needs to adapt the UI from what you did before ",
          priority: "completed",
          comments: 12,
          files: 15,
          users: ["person1", "person3", "person2"],
          status: "completed",
        },
      ],
      favColor: "#E4CCFD",
    },
    {
      id: "task4",
      title: "Wireframes",
      toDos: [
        {
          id: "1",
          title: "Brainstorming",
          image: [],
          description:
            "Brainstorming brings team members' diverse experience into play. ",
          priority: "low",
          comments: 12,
          files: 0,
          users: ["person1", "person3", "person2"],
          status: "not started",
        },
        {
          id: 2,
          title: "Research",
          image: [],
          description:
            "User research helps you to create an optimal product for users.",
          priority: "high",
          comments: 10,
          files: 3,
          users: ["person4", "person3"],
          status: "not started",
        },
        {
          id: 3,
          title: "Wireframes",
          image: [],
          description:
            "Low fidelity wireframes include the most basic content and visuals.",
          priority: "high",
          comments: 11,
          files: 1,
          users: ["person1", "person3", "person2"],
          status: "not started",
        },
        {
          id: 4,
          title: "Onboarding Illustrations",
          image: ["Onboarding"],
          description: "",
          priority: "low",
          comments: 14,
          files: 15,
          users: ["person3", "person2", "person1"],
          status: "started",
        },
        {
          id: 5,
          title: "Moodboard",
          image: ["Moodboard1", "Moodboard2"],
          description: "",
          priority: "low",
          comments: 9,
          files: 10,
          users: ["person3"],
          status: "started",
        },
        {
          id: 6,
          title: "Mobile App Design",
          image: ["MobileAppDesign"],
          description: "",
          priority: "completed",
          comments: 12,
          files: 15,
          users: ["person3", "person2"],
          status: "completed",
        },
        {
          id: 7,
          title: "Design System",
          image: [],
          description: "It just needs to adapt the UI from what you did before ",
          priority: "completed",
          comments: 12,
          files: 15,
          users: ["person1", "person3", "person2"],
          status: "completed",
        },
      ],
      favColor: "#76A5EA",
    },
  ];
  